import './components/hero.js'
import './components/icons-list.js'
import './components/logo.js'
import './components/menu.js'
import './components/form.js'
import './components/gallery-product.js'
import './components/category-filter.js'
import './components/row.js'
